# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 22) do

  create_table "actions", :force => true do |t|
    t.column "name", :string, :limit => 40
  end

  create_table "companies", :force => true do |t|
    t.column "type", :string
    t.column "name", :string, :limit => 50
    t.column "address1", :string, :limit => 100
    t.column "address2", :string, :limit => 100
    t.column "city", :string, :limit => 50
    t.column "state_id", :integer
    t.column "zip", :string, :limit => 10
    t.column "phone", :string, :limit => 20
    t.column "fax", :string, :limit => 20
    t.column "image_url", :string, :limit => 250
    t.column "website", :string, :limit => 200
    t.column "wiki", :string, :limit => 200
    t.column "maildomain", :string, :limit => 80
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "turn_up", :datetime
    t.column "vcio", :datetime
    t.column "ceo_name", :string, :limit => 50
    t.column "ceo_phone", :string, :limit => 20
    t.column "contact_name", :string, :limit => 50
    t.column "contact_phone", :string, :limit => 20
    t.column "contracted_users", :integer
  end

  create_table "difficulties", :force => true do |t|
    t.column "name", :string
    t.column "level", :integer
  end

  create_table "priorities", :force => true do |t|
    t.column "name", :string, :limit => 60
    t.column "digit", :string, :limit => 10
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
    t.column "type", :string
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "states", :force => true do |t|
    t.column "short_name", :string, :limit => 2
    t.column "long_name", :string, :limit => 20
  end

  create_table "statistics", :force => true do |t|
    t.column "user_id", :integer
    t.column "ticket_id", :integer
    t.column "pending_time", :float
    t.column "contacted_time", :float
    t.column "open_time", :float
    t.column "total_time", :float
    t.column "engineer_id", :integer
  end

  create_table "statuses", :force => true do |t|
    t.column "name", :string, :limit => 15
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id", :integer
    t.column "taggable_id", :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "ticket_updates", :force => true do |t|
    t.column "created_at", :datetime
    t.column "comment", :text
    t.column "user_id", :integer
    t.column "ticket_id", :integer
    t.column "time_spent", :integer
    t.column "action_id", :integer
    t.column "file", :string, :limit => 150
  end

  add_index "ticket_updates", ["ticket_id"], :name => "ticket_id"
  add_index "ticket_updates", ["user_id"], :name => "ticket_updates_user_id"
  add_index "ticket_updates", ["created_at"], :name => "ticket_updates_created_at"
  add_index "ticket_updates", ["ticket_id", "created_at"], :name => "ticket_updates_ticket_id_created_at"

  create_table "tickets", :force => true do |t|
    t.column "subject", :string, :limit => 200
    t.column "user_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "priority_id", :integer
    t.column "status_id", :integer
    t.column "engineer_id", :integer
    t.column "body", :text
    t.column "difficulty_id", :integer
  end

  add_index "tickets", ["engineer_id"], :name => "tickets_engineer_id"
  add_index "tickets", ["status_id"], :name => "tickets_status_id"
  add_index "tickets", ["user_id"], :name => "tickets_user_id"

  create_table "users", :force => true do |t|
    t.column "first_name", :string, :limit => 50
    t.column "last_name", :string, :limit => 50
    t.column "password_hash", :string
    t.column "password_salt", :string, :limit => 40
    t.column "email", :string, :limit => 100
    t.column "office_phone", :string, :limit => 20
    t.column "cell_phone", :string, :limit => 20
    t.column "home_phone", :string, :limit => 20
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "status", :string
    t.column "last_login", :datetime
    t.column "type", :string, :limit => 25
    t.column "instant_messaging", :string, :limit => 250
    t.column "company_id", :integer
    t.column "role_id", :integer
    t.column "text_password", :string
  end

end
